version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abook
    ports:
      - 5432:5432
    volumes:
      - abook:/var/lib/postgresql/data
volumes:
  abook:
